# -*- coding: utf-8 -*-
"""A_53_Practical_1_TicTacToe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJSZmq_C9OwFkDHry51MmQPioyaplrLR

# Practical 1 - Artificial Intelligence Lab 

## Name: Prathamesh Rajbhoj

## Roll No: A - 53
"""

import math

def printGrid(grid, rows, cols):
    print("Current Game\n\n")
    for i in range(rows):
        print(grid[i])

def checkWinner(grid,rows,cols,x):


    if(grid[0][0]==x and grid[0][1]==x and grid[0][2]==x):
        return True

    if(grid[1][0]==x and grid[1][1]==x and grid[1][2]==x):
        return True

    if(grid[2][0]==x and grid[2][1]==x and grid[2][2]==x):
        return True





    if(grid[0][0]==x and grid[1][0]==x and grid[2][0]==x):
        return True

    if(grid[0][1]==x and grid[1][1]==x and grid[2][1]==x):
        return True

    if(grid[0][2]==x and grid[1][2]==x and grid[2][2]==x):
        return True



    if(grid[0][0]==x and grid[1][1]==x and grid[2][2]==x):
        return True

    if(grid[0][2]==x and grid[1][1]==x and grid[2][0]==x):
        return True
            
    return False

def printChoices(grid, rows, cols):
    
    lst = []
    
    for i in range(rows):
        for j in range(cols):
            if(grid[i][j]==0):
                pair = (i+1,j+1)
                lst.append(pair)
    
    if(len(lst)==0):
        print("No Choices Available")
    else:
        print("Choices Available : ")
        print(*sorted(lst))

def checkValidity(x,y,rows,cols):
    if(x>=0 and x<rows and y>=0 and y<cols):
        return True;
    else:
        return False;

# Starting main code

if __name__ == "__main__":
    print("Welcome to Tic Tac Toe")
    
    rows = 3
    cols = 3
    
    grid = [[0,0,0],[0,0,0],[0,0,0]]
    
    
    loop = 9
    currPlayer = 1
    
    for chance in range(loop):
        
        print("\n\n")
        printGrid(grid, rows, cols)
        print("\n\n")
    
        
        print("Player ", currPlayer, " chance \n\n")
        
        printChoices(grid, rows, cols)
        x,y = input("Enter where you want to play : ").split()
        
        x = int(x)
        y = int(y)
        
        # print(x,y)
        
        x=x-1
        y=y-1
        
        
        if(checkValidity(x,y,rows,cols)==False):
            print("Invalid input")
            continue
    
        if(grid[x][y]==0):
            grid[x][y] = currPlayer
            
            
            if(checkWinner(grid, rows, cols,currPlayer)==True):
                print("Player ", currPlayer, " Won")
                break
            
            currPlayer = currPlayer % 2
            currPlayer = currPlayer+1
        else:
            print("Invalid input")
        
        if(chance==loop-1):
          print("tieeee")

