# -*- coding: utf-8 -*-
"""A_53_AI_Practical7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xau0jsMmwjr_-2ntWfjcio7UGeI9jg9N
"""

features = ["AGE", "INCOME", "STUDENT", "CREDIT_RATING", "CLASS"]

dataset = [
    ["junior", "high", "no", "fair", "NO"],
    ["junior", "high", "no", "excellent", "NO"],
    ["middle", "high", "no", "fair", "YES"],
    ["senior", "medium", "no", "fair", "YES"],
    ["senior", "low", "yes", "fair", "YES"],

    ["senior", "low", "yes", "excellent", "NO"],
    ["middle", "low", "yes", "excellent", "YES"],
    ["junior", "medium", "no", "fair", "NO"],
    ["junior", "low", "yes", "fair", "YES"],
    ["senior", "medium", "yes", "fair", "YES"],

    ["junior", "medium", "yes", "excellent", "YES"],
    ["middle", "medium", "no", "excellent", "YES"],
    ["middle", "high", "yes", "fair", "YES"],
    ["senior", "medium", "no", "excellent", "NO"],

]

age_matrix = {
    "junior": 0,
    "middle": 0,
    "senior": 0
}

age_matrix_yes = {
    "junior": 0,
    "middle": 0,
    "senior": 0
}



income_matrix = {
    "high": 0,
    "medium": 0,
    "low": 0,
}

income_matrix_yes = {
    "high": 0,
    "medium": 0,
    "low": 0,
}



student_matrix = {
    "yes" : 0,
    "no" : 0
}
student_matrix_yes = {
    "yes" : 0,
    "no" : 0
}

rating_matrix = {
    "fair": 0,
    "excellent": 0
}
rating_matrix_yes = {
    "fair": 0,
    "excellent": 0
}

for i in range(len(dataset)):

  curr = dataset[i]



  age_matrix[curr[0]] = age_matrix[curr[0]] + 1

  income_matrix[curr[1]] = income_matrix[curr[1]] + 1

  student_matrix[curr[2]] = student_matrix[curr[2]] + 1

  rating_matrix[curr[3]] = rating_matrix[curr[3]] + 1


  if(curr[4]=="YES"):
    age_matrix_yes[curr[0]] = age_matrix_yes[curr[0]] + 1

  if(curr[4]=="YES"):
    income_matrix_yes[curr[1]] = income_matrix_yes[curr[1]] + 1

  if(curr[4]=="YES"):
    student_matrix_yes[curr[2]] = student_matrix_yes[curr[2]] + 1

  if(curr[4]=="YES"):
    rating_matrix_yes[curr[3]] = rating_matrix_yes[curr[3]] + 1

print(age_matrix)
print(income_matrix)
print(student_matrix)
print(rating_matrix)

print(age_matrix_yes)
print(income_matrix_yes)
print(student_matrix_yes)
print(rating_matrix_yes)

conditions = ["junior", "high", "no", "fair"]

count_yes = 9
count_no = 5

num = 1
den = 1

num = num * (age_matrix_yes[conditions[0]])
num = num * (income_matrix_yes[conditions[1]])
num = num * (student_matrix_yes[conditions[2]])
num = num * (rating_matrix_yes[conditions[3]])

den = den * count_yes
den = den * count_yes
den = den * count_yes
den = den * count_yes

ans = num/den

ans = ans * (count_yes / (count_yes + count_no))

print("Probability of YES : ", ans)

num = 1
den = 1

num = num * (age_matrix[conditions[0]] - age_matrix_yes[conditions[0]])
num = num * (income_matrix[conditions[1]] - income_matrix_yes[conditions[1]])
num = num * (student_matrix[conditions[2]] - student_matrix_yes[conditions[2]])
num = num * (rating_matrix[conditions[3]] - rating_matrix_yes[conditions[3]])

den = den * count_no
den = den * count_no
den = den * count_no
den = den * count_no

ans = num/den

ans = ans * (count_no / (count_yes + count_no))

print("Probability of No : ", ans)

